### PR TITLE
Fix compacting of paragraphs containing self-closing angle bracket components

### PR DESCRIPTION
**Pull request by jrowlingson**
Closes https://github.com/ember-learn/ember-cli-addon-docs/issues/360

### CODE REVIEW

**Comment by jrowlingson** [comment]
It looks like the build needs a restart.

**Comment by barryofguilder** [comment]
Looking forward to getting this merged as I'm running into this issue right now.

**Comment by crixx** [comment]
@jrowlingson How can we help getting this merged?

**Comment by jrowlingson** [comment]
@crixx I build needs a restart

**Pull request merged**
