### PR TITLE
Update to ember-router-scroll v4

### LINKED ISSUE #766: `setupRouter` deprecation warning
The browser console shows the following warning on the latest version:

`DEPRECATION: The use of Ember.Router in setupRouter is deprecated. Please use the router service. [deprecation id: ember-app-scheduler.setupRouter]`

Updating to ember-router-scroll v4 [should fix that](https://github.com/DockYard/ember-router-scroll/blob/master/CHANGELOG.md#400).

### PR DESCRIPTION
**Pull request by Windvis**
Closes #766

### CODE REVIEW

**Comment by Windvis** [comment]
Hmm, not sure what's going on in the failing test case.

**Comment by rwwagner90** [comment]
@Windvis looks like `ember-maybe-import-regenerator` is missing from this addons devDeps. I think we need to change it here https://github.com/ember-learn/ember-cli-addon-docs/blob/master/test-apps/new-addon/package.json#L41

It should be `ember-maybe-import-regenerator-for-testing`

**Comment by Windvis** [comment]
> @Windvis looks like `ember-maybe-import-regenerator` is missing from this addons devDeps. I think we need to change it here https://github.com/ember-learn/ember-cli-addon-docs/blob/master/test-apps/new-addon/package.json#L41
> 
> It should be `ember-maybe-import-regenerator-for-testing`

Seems like that indeed was the issue. Thanks!

**Review by rwwagner90 — APPROVED** [review]

**Comment by rwwagner90** [comment]
Thanks for the PR @Windvis! 🎉

**Pull request merged**
