### PR TITLE
Linkable live docs

### PR DESCRIPTION
**Pull request by manudwarf**
This pull request adds an anchor link.
The hover animation is to make the purpose of the anchor more obvious, otherwise it seemed to have caused some confusion.
I am very open to suggestions on how to make these elements more configurable if you'd prefer.

### CODE REVIEW

**Comment by manudwarf** [comment]
Any news on this? :)

**Comment by pzuraq** [comment]
There's actually already a style implementation of this in API docs, so I think we should make sure both of them the same. I hacked it out in an afternoon so unsure which solution is better, need to take a look

**Comment by manudwarf** [comment]
Hi,

I wanted to know if anyone has taken a look at this?

Thanks

**Comment by pzuraq** [comment]
Hey @manudwarf, we just merged a large redesign so we haven't had a chance to look at this. It'll likely need to be rebased and combined with the link tags used in API docs already. I'll have a chance to look at it on Friday

**Comment by samselikoff** [comment]
@manudwarf sorry about the delayed response!

If we add a link to demos I'd like to think through the design a bit.

First question, though: if section headings were linkable would that be sufficient for your use case? This is definitely a planned feature and I think is more common in these types of sites than linking directly to the actual snippets.

**Comment by pzuraq** [comment]
Hey @manudwarf, we ended up addressing this and integrating it with the right-hand sidebar nav, you can check it out on the docs site now! Thanks again for suggesting this feature 😄

**Pull request closed without merging**
