### PR TITLE
embroider ready

### PR DESCRIPTION
**Pull request by patricklx**
this is a way to support embroider and classic build.

as postprocessTree does not exists for embroider, alternative ways where needed.

The drawback.of this could be that if some other type of files would be converted to .md files as those would not be picked up.
And other files that could be converted to hbs files

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@patricklx looks like CI is unhappy with proposed changes :/

**Comment by patricklx** [comment]
@SergeAstapov try again

**Comment by patricklx** [comment]
Ah, lock file issue and linter... Will fix it later

**Comment by patricklx** [comment]
fixed lock file issue

**Comment by patricklx** [comment]
i had to move babel.config.js inside eslint.rc file as it was breaking embroider build

**Comment by patricklx** [comment]
it should now all work

**Review by ef4 — APPROVED** [review]
Replacing postprocessTree('all') with treeForPublic and treeForAddon is good.

**Review by SergeAstapov — APPROVED** [review]

**Review by RobbieTheWagner — APPROVED** [review]
LGTM! I thought we had no way to support embroider

**Pull request merged**
