### PR TITLE
Fix usage of a test selector on a tagless component

### PR DESCRIPTION
**Pull request by czosel**
This is just an updated version of #271, because I'm currently blocked by this issue and would like it to land.

### CODE REVIEW

**Comment by czosel** [comment]
Looks like the CI issue magically resolved itself! :tada:

**Comment by czosel** [comment]
The `--no-lockfile` build fails because of https://github.com/ember-app-scheduler/ember-app-scheduler/issues/261

**Comment by dfreeman** [comment]
Thanks  @czosel, and sorry this issue has lingered for so long!

**Comment by czosel** [comment]
No worries, thanks for merging! :slightly_smiling_face:

**Pull request merged**
