### PR TITLE
update controllers syntax

### PR DESCRIPTION
**Pull request by miguelcobain**
Not much here, but trying to update the various addon parts one at a time.
I removed the `addon/controllers/docs/api/class.js` controller, since I didn't see any usage of it.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
`test-apps/new-addon/tests/dummy/app/controllers/route-using-compile-markdown.js` looks good!

would leave call about `docs/api/class` controller to @rwwagner90

**Comment by rwwagner90** [comment]
@miguelcobain I would think that controller would be used somewhere, but I don't know. Looks like to me it's the controller to automatically generated method names for the auto generated docs?

**Comment by miguelcobain** [comment]
@rwwagner90 a global search for `methodParams` yields no results in the whole repository.
Would that controller be used on the consuming app?

**Comment by rwwagner90** [comment]
@miguelcobain perhaps you are right. It could be a leftover thing.

**Comment by miguelcobain** [comment]
@rwwagner90 tried searching on ember observer for `methodParams`. No results that seem to use this. Same for `docs/api/class`, so nothing is importing the controller.

**Review by rwwagner90 — APPROVED** [review]

**Pull request merged**
