### PR TITLE
Add id to example component

### PR DESCRIPTION
**Pull request by manudwarf**
Hi!

We wanted to be able to link to specific examples in a give page. Would this addition be ok?

### CODE REVIEW

**Comment by samselikoff** [comment]
Hm I tend to think of `elementId` as private API to Ember...

@dfreeman thoughts?

**Comment by manudwarf** [comment]
According to the doc, it is public:
https://emberjs.com/api/ember/2.18/classes/Component/properties/elementId?anchor=elementId

**Comment by dfreeman** [comment]
👍  Seems reasonable to me. As a tiny nit, it might be more correct to use `init()` than `didReceiveAttrs()`, since `elementId` becomes read-only after the first render.

**Comment by samselikoff** [comment]
Wow, TIL. Let's change it to `init` and then we can merge away!

Thanks for the contrib!

**Comment by manudwarf** [comment]
Fixed :)

On a separate note, the reason why I'm suggesting this change is because we want live examples to be linkable in our docs.
I will come back with an additional pull request for a linkable anchor. Is there anything in particular I should pay attention to? Do you want such a feature to be configurable, hidden/shown by default?

**Comment by samselikoff** [comment]
Hmm. Now I'm looking at Bootstrap's site and wondering, could we just link to headings?

https://getbootstrap.com/docs/4.0/components/card/#example

That's already on the docket, but I'm wondering if all h1s, h2s and h3s were linkable would it solve your use case? Could you just put heading above each example you wanted to provide a link to?

**Pull request merged**
